import { db } from '../src/database/connection.js';
import { models, pgVectorExtension } from '../src/database/schema.js';
import { logger } from '../src/utils/logger.js';
import { sql } from 'drizzle-orm';

// Model data extracted from seed-models.sql
const modelsData = [
  // GROQ MODELS (Default)
  {
    modelId: 'llama-3.3-70b-versatile',
    name: 'Llama 3.3 70B Versatile (Groq)',
    provider: 'Groq',
    description: '⚡ 280 tok/s - Most capable Llama 3.3, 131K context',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning'],
    maxTokens: 32768,
    cost: '$0.59/1M in + $0.79/1M out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 1,
  },
  // OLLAMA MODELS (Local)
  {
    modelId: 'llama2:7b',
    name: 'Llama 2 7B (Local)',
    provider: 'Ollama',
    description: '🏠 Local - Fast, free, private. No API costs!',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 4096,
    cost: 'Free',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 10,
  },
  {
    modelId: 'llama2:13b',
    name: 'Llama 2 13B (Local)',
    provider: 'Ollama',
    description: '🏠 Local - Better quality, still free and private',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning'],
    maxTokens: 4096,
    cost: 'Free',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 11,
  },
  {
    modelId: 'mistral:7b',
    name: 'Mistral 7B (Local)',
    provider: 'Ollama',
    description: '🏠 Local - Excellent instruction following, multilingual',
    capabilities: ['Text', 'Code', 'Analysis', 'Multilingual'],
    maxTokens: 8192,
    cost: 'Free',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 12,
  },
  {
    modelId: 'codellama:7b',
    name: 'Code Llama 7B (Local)',
    provider: 'Ollama',
    description: '🏠 Local - Specialized for code generation and analysis',
    capabilities: ['Code', 'Text', 'Analysis'],
    maxTokens: 16384,
    cost: 'Free',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 13,
  },
  {
    modelId: 'phi:latest',
    name: 'Microsoft Phi-2 (Local)',
    provider: 'Ollama',
    description: '🏠 Local - Small, fast, efficient for most tasks',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 2048,
    cost: 'Free',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 14,
  },
  // OPENAI MODELS
  {
    modelId: 'gpt-4-turbo',
    name: 'GPT-4 Turbo',
    provider: 'OpenAI',
    description: 'Latest GPT-4 with 128K context, vision, and JSON mode',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning', 'Vision'],
    maxTokens: 128000,
    cost: '$0.01/1K in + $0.03/1K out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 2,
  },
  {
    modelId: 'gpt-4',
    name: 'GPT-4',
    provider: 'OpenAI',
    description: 'Original GPT-4, most capable reasoning model',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning'],
    maxTokens: 8192,
    cost: '$0.03/1K in + $0.06/1K out',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 3,
  },
  {
    modelId: 'gpt-3.5-turbo',
    name: 'GPT-3.5 Turbo',
    provider: 'OpenAI',
    description: 'Fast and affordable, great for most tasks',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 16385,
    cost: '$0.0005/1K in + $0.0015/1K out',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 4,
  },
  // ANTHROPIC MODELS
  {
    modelId: 'claude-3-sonnet',
    name: 'Claude 3 Sonnet',
    provider: 'Anthropic',
    description: 'Balanced performance with strong reasoning capabilities',
    capabilities: ['Text', 'Analysis', 'Code', 'Creative Writing'],
    maxTokens: 200000,
    cost: '$0.003/1K tokens',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 5,
  },
  // GROQ MODELS - Llama 4 Series
  {
    modelId: 'meta-llama/llama-4-scout-17b-16e-instruct',
    name: 'Llama 4 Scout 17B (Groq)',
    provider: 'Groq',
    description: '🚀 FASTEST! 750 tok/s - Ideal for summarization, reasoning, code',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning', 'Summarization'],
    maxTokens: 8192,
    cost: '$0.11/1M in + $0.34/1M out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: true,
    sortOrder: 6,
  },
  {
    modelId: 'meta-llama/llama-4-maverick-17b-128e-instruct',
    name: 'Llama 4 Maverick 17B (Groq)',
    provider: 'Groq',
    description: '🌍 600 tok/s - Multilingual & multimodal, great for assistants',
    capabilities: ['Text', 'Code', 'Multilingual', 'Creative Writing', 'Chat'],
    maxTokens: 8192,
    cost: '$0.20/1M in + $0.60/1M out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 7,
  },
  // Llama 3.1 Series
  {
    modelId: 'llama-3.1-8b-instant',
    name: 'Llama 3.1 8B Instant (Groq)',
    provider: 'Groq',
    description: '⚡⚡ 560 tok/s - Ultra-fast, most cost-effective',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 131072,
    cost: '$0.05/1M in + $0.08/1M out',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 8,
  },
  // OpenAI Open Models on Groq
  {
    modelId: 'openai/gpt-oss-120b',
    name: 'GPT-OSS 120B (Groq)',
    provider: 'Groq',
    description: '500 tok/s - OpenAI open model, strong general performance',
    capabilities: ['Text', 'Code', 'Analysis', 'Reasoning'],
    maxTokens: 65536,
    cost: '$0.15/1M in + $0.60/1M out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 9,
  },
  {
    modelId: 'openai/gpt-oss-20b',
    name: 'GPT-OSS 20B (Groq)',
    provider: 'Groq',
    description: '⚡ 1000 tok/s - Fast OpenAI open model, great value',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 65536,
    cost: '$0.075/1M in + $0.30/1M out',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 15,
  },
  // Groq Compound Systems
  {
    modelId: 'groq/compound',
    name: 'Groq Compound (Groq)',
    provider: 'Groq',
    description: '450 tok/s - Advanced reasoning system with compound intelligence',
    capabilities: ['Text', 'Reasoning', 'Analysis', 'Problem Solving'],
    maxTokens: 8192,
    cost: 'Contact for pricing',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 16,
  },
  {
    modelId: 'groq/compound-mini',
    name: 'Groq Compound Mini (Groq)',
    provider: 'Groq',
    description: '450 tok/s - Lightweight compound reasoning system',
    capabilities: ['Text', 'Reasoning', 'Analysis'],
    maxTokens: 8192,
    cost: 'Contact for pricing',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 17,
  },
  // Other Open Models on Groq
  {
    modelId: 'qwen/qwen3-32b',
    name: 'Qwen 3 32B (Groq)',
    provider: 'Groq',
    description: '400 tok/s - Alibaba Qwen 3, excellent for multilingual tasks',
    capabilities: ['Text', 'Code', 'Multilingual', 'Analysis'],
    maxTokens: 40960,
    cost: '$0.29/1M in + $0.59/1M out',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 18,
  },
  {
    modelId: 'moonshotai/kimi-k2-instruct-0905',
    name: 'Kimi K2 (Groq)',
    provider: 'Groq',
    description: '200 tok/s - 262K context! Moonshot AI model for long documents',
    capabilities: ['Text', 'Long Context', 'Analysis', 'Document Processing'],
    maxTokens: 16384,
    cost: '$1.00/1M in + $3.00/1M out',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 19,
  },
  // Legacy Groq Models
  {
    modelId: 'mixtral-8x7b-32768',
    name: 'Mixtral 8x7B (Groq)',
    provider: 'Groq',
    description: 'Fast Mixtral mixture-of-experts, 32K context',
    capabilities: ['Text', 'Code', 'Analysis', 'Multilingual'],
    maxTokens: 32768,
    cost: '$0.24/1M tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 20,
  },
  {
    modelId: 'gemma2-9b-it',
    name: 'Gemma 2 9B (Groq)',
    provider: 'Groq',
    description: 'Google Gemma 2 9B - efficient and fast',
    capabilities: ['Text', 'Code', 'Analysis'],
    maxTokens: 8192,
    cost: '$0.20/1M tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 21,
  },
  // Whisper Models (Speech-to-Text)
  {
    modelId: 'whisper-large-v3',
    name: 'Whisper Large V3 (Groq)',
    provider: 'Groq',
    description: '🎤 Speech-to-text model for audio transcription',
    capabilities: ['Speech-to-Text', 'Audio', 'Transcription'],
    maxTokens: 448,
    cost: '$0.006/1K tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 30,
  },
  {
    modelId: 'whisper-large-v3-turbo',
    name: 'Whisper Large V3 Turbo (Groq)',
    provider: 'Groq',
    description: '🎤⚡ Fast speech-to-text model for real-time transcription',
    capabilities: ['Speech-to-Text', 'Audio', 'Real-time'],
    maxTokens: 448,
    cost: '$0.006/1K tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 31,
  },
  // PlayAI TTS Models
  {
    modelId: 'playai-tts',
    name: 'PlayAI TTS (Groq)',
    provider: 'Groq',
    description: '🔊 Text-to-speech model for voice synthesis',
    capabilities: ['Text-to-Speech', 'Voice', 'Audio Generation'],
    maxTokens: 8192,
    cost: 'Contact for pricing',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 32,
  },
  {
    modelId: 'playai-tts-arabic',
    name: 'PlayAI TTS Arabic (Groq)',
    provider: 'Groq',
    description: '🔊🇸🇦 Arabic text-to-speech model',
    capabilities: ['Text-to-Speech', 'Arabic', 'Voice'],
    maxTokens: 8192,
    cost: 'Contact for pricing',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 33,
  },
  // Meta Llama Guard Models
  {
    modelId: 'meta-llama/llama-guard-4-12b',
    name: 'Llama Guard 4 12B (Groq)',
    provider: 'Groq',
    description: '🛡️ Safety guard model for content filtering',
    capabilities: ['Safety', 'Content Filtering', 'Moderation'],
    maxTokens: 1024,
    cost: '$0.20/1M tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 34,
  },
  {
    modelId: 'meta-llama/llama-prompt-guard-2-22m',
    name: 'Llama Prompt Guard 2 22M (Groq)',
    provider: 'Groq',
    description: '🛡️ Lightweight prompt safety guard',
    capabilities: ['Safety', 'Prompt Filtering'],
    maxTokens: 512,
    cost: '$0.10/1M tokens',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 35,
  },
  {
    modelId: 'meta-llama/llama-prompt-guard-2-86m',
    name: 'Llama Prompt Guard 2 86M (Groq)',
    provider: 'Groq',
    description: '🛡️ Enhanced prompt safety guard',
    capabilities: ['Safety', 'Prompt Filtering', 'Moderation'],
    maxTokens: 512,
    cost: '$0.15/1M tokens',
    speed: 'fast' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 36,
  },
  // Additional Moonshot Models
  {
    modelId: 'moonshotai/kimi-k2-instruct',
    name: 'Kimi K2 Instruct (Groq)',
    provider: 'Groq',
    description: '🌙 Moonshot AI model with 131K context',
    capabilities: ['Text', 'Long Context', 'Analysis'],
    maxTokens: 16384,
    cost: '$0.80/1M in + $2.40/1M out',
    speed: 'medium' as const,
    quality: 'high' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 37,
  },
  // SDAIA Models
  {
    modelId: 'allam-2-7b',
    name: 'Allam 2 7B (Groq)',
    provider: 'Groq',
    description: '🇸🇦 Saudi AI model for Arabic language tasks',
    capabilities: ['Text', 'Arabic', 'Multilingual'],
    maxTokens: 4096,
    cost: '$0.15/1M tokens',
    speed: 'fast' as const,
    quality: 'medium' as const,
    isAvailable: true,
    isFeatured: false,
    sortOrder: 38,
  },
];

async function seedDatabase() {
  try {
    logger.info('🌱 Starting database seeding...');

    // Insert models
    logger.info(`Inserting ${modelsData.length} models...`);
    for (const modelData of modelsData) {
      await db
        .insert(models)
        .values(modelData)
        .onConflictDoNothing({ target: models.modelId });
    }
    logger.info('✅ Models inserted successfully');

    // Insert vector extension marker
    logger.info('Inserting vector extension marker...');
    await db
      .insert(pgVectorExtension)
      .values({ id: 'pgvector' })
      .onConflictDoNothing({ target: pgVectorExtension.id });
    logger.info('✅ Vector extension marker inserted');

    // Verify counts
    const modelCount = await db.execute(sql`SELECT COUNT(*) as count FROM models`);
    const vectorExtCount = await db.execute(sql`SELECT COUNT(*) as count FROM vector_extension`);

    logger.info('\n📊 Verification:');
    logger.info(`   Models: ${modelCount.rows[0].count}`);
    logger.info(`   Vector Extension: ${vectorExtCount.rows[0].count}`);

    logger.info('\n✅ Database seeding completed successfully!');
    process.exit(0);
  } catch (error) {
    logger.error('❌ Database seeding failed:', error);
    process.exit(1);
  }
}

// Run the seed function
seedDatabase();

