import React, { useState, useRef, useEffect } from 'react';
import { History, Plus, MoreVertical, FileText, FileJson, File, Command, Edit2, Sparkles, Check, X, Loader2 } from 'lucide-react';
import { Message } from '../../types';
import { exportChatAsMarkdown, exportChatAsJSON, exportChatAsText } from '../../utils/exportChat';
import { showSuccess, showError } from '../../utils/toast';
import { useSessionManagement } from '../../hooks/useSessionManagement';

interface ChatHeaderProps {
  sessionId?: string;
  sessionTitle: string;
  onNewChat: () => void;
  onToggleHistory: () => void;
  showHistory: boolean;
  messageCount: number;
  messages?: Message[];
  onBackToWelcome?: () => void;
  onTitleUpdate?: (newTitle: string) => void;
  autoGenerated?: boolean;
}

export function ChatHeader({
  sessionId,
  sessionTitle,
  onNewChat,
  onToggleHistory,
  showHistory,
  messageCount,
  messages = [],
  onBackToWelcome,
  onTitleUpdate,
  autoGenerated = false,
}: ChatHeaderProps) {
  const [showMenu, setShowMenu] = useState(false);
  const [isEditingTitle, setIsEditingTitle] = useState(false);
  const [editedTitle, setEditedTitle] = useState(sessionTitle);
  const [isGeneratingTitle, setIsGeneratingTitle] = useState(false);
  const titleInputRef = useRef<HTMLInputElement>(null);
  
  const { updateTitle, generateTitle } = useSessionManagement();

  useEffect(() => {
    setEditedTitle(sessionTitle);
  }, [sessionTitle]);

  useEffect(() => {
    if (isEditingTitle && titleInputRef.current) {
      titleInputRef.current.focus();
      titleInputRef.current.select();
    }
  }, [isEditingTitle]);

  const handleExport = (format: 'markdown' | 'json' | 'text') => {
    switch (format) {
      case 'markdown':
        exportChatAsMarkdown(messages, sessionTitle);
        break;
      case 'json':
        exportChatAsJSON(messages, sessionTitle);
        break;
      case 'text':
        exportChatAsText(messages, sessionTitle);
        break;
    }
    showSuccess(`Exported as ${format.toUpperCase()}`);
    setShowMenu(false);
  };

  const handleSaveTitle = async () => {
    if (!sessionId || !editedTitle.trim() || editedTitle === sessionTitle) {
      setIsEditingTitle(false);
      setEditedTitle(sessionTitle);
      return;
    }

    try {
      await updateTitle(sessionId, editedTitle.trim(), false);
      onTitleUpdate?.(editedTitle.trim());
      showSuccess('Title updated successfully');
      setIsEditingTitle(false);
    } catch (error) {
      console.error('Failed to update title:', error);
      showError('Failed to update title');
      setEditedTitle(sessionTitle);
      setIsEditingTitle(false);
    }
  };

  const handleCancelEdit = () => {
    setEditedTitle(sessionTitle);
    setIsEditingTitle(false);
  };

  const handleGenerateTitle = async () => {
    if (!sessionId || messageCount < 2) {
      showError('Need at least 2 messages to generate a title');
      return;
    }

    setIsGeneratingTitle(true);
    try {
      const updatedSession = await generateTitle(sessionId);
      onTitleUpdate?.(updatedSession.title);
      showSuccess('Title generated successfully');
    } catch (error) {
      console.error('Failed to generate title:', error);
      showError('Failed to generate title');
    } finally {
      setIsGeneratingTitle(false);
    }
  };

  const handleTitleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === 'Enter') {
      handleSaveTitle();
    } else if (e.key === 'Escape') {
      handleCancelEdit();
    }
  };

  return (
    <div className="flex items-center justify-between px-6 py-3 border-b border-gray-100 bg-white">
          <div className="flex items-center gap-3">
            {onBackToWelcome && (
              <button
                onClick={onBackToWelcome}
                className="p-2 rounded-lg transition-colors hover:bg-gray-100 text-gray-600"
                title="Back to LLM Hub"
              >
                <Command className="w-4 h-4" />
              </button>
            )}
            
            <button
              onClick={onToggleHistory}
              className={`p-2 rounded-lg transition-colors ${
                showHistory ? 'bg-teal-50 text-joa-primary' : 'hover:bg-gray-100 text-gray-600'
              }`}
              title={showHistory ? 'Hide conversation history' : 'Show conversation history'}
            >
              <History className="w-4 h-4" />
            </button>
        
        <div className="flex items-center gap-2 min-w-0">
          {isEditingTitle ? (
            /* Edit Mode */
            <div className="flex items-center gap-2">
              <input
                ref={titleInputRef}
                type="text"
                value={editedTitle}
                onChange={(e) => setEditedTitle(e.target.value)}
                onKeyDown={handleTitleKeyDown}
                onBlur={handleSaveTitle}
                className="px-2 py-1 text-sm font-semibold bg-white border border-joa-primary rounded focus:outline-none focus:ring-2 focus:ring-joa-primary"
                placeholder="Enter title..."
              />
              <button
                onClick={handleSaveTitle}
                className="p-1 text-green-600 hover:bg-green-50 rounded transition-colors"
                title="Save title"
              >
                <Check className="w-4 h-4" />
              </button>
              <button
                onClick={handleCancelEdit}
                className="p-1 text-gray-500 hover:bg-gray-100 rounded transition-colors"
                title="Cancel"
              >
                <X className="w-4 h-4" />
              </button>
            </div>
          ) : (
            /* Display Mode */
            <div className="group flex items-center gap-2 min-w-0">
              <div className="min-w-0 flex-1">
                <div className="flex items-center gap-2">
                  <h2 className="text-sm font-semibold text-gray-900 truncate">{sessionTitle}</h2>
                  {autoGenerated && (
                    <span className="flex-shrink-0 inline-flex items-center px-1.5 py-0.5 bg-purple-50 text-purple-700 rounded text-xs">
                      <Sparkles className="w-3 h-3 mr-0.5" />
                      AI
                    </span>
                  )}
                </div>
                {messageCount > 0 && (
                  <p className="text-xs text-gray-500">{messageCount} messages</p>
                )}
              </div>
              
              {/* Title Actions - Show on hover */}
              {sessionId && messageCount > 0 && (
                <div className="flex-shrink-0 flex items-center gap-1 opacity-0 group-hover:opacity-100 transition-opacity">
                  <button
                    onClick={() => setIsEditingTitle(true)}
                    className="p-1 text-gray-400 hover:text-gray-600 hover:bg-gray-100 rounded transition-colors"
                    title="Edit title"
                  >
                    <Edit2 className="w-3.5 h-3.5" />
                  </button>
                  <button
                    onClick={handleGenerateTitle}
                    disabled={isGeneratingTitle || messageCount < 2}
                    className="p-1 text-gray-400 hover:text-purple-600 hover:bg-purple-50 rounded transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
                    title="Generate title with AI"
                  >
                    {isGeneratingTitle ? (
                      <Loader2 className="w-3.5 h-3.5 animate-spin" />
                    ) : (
                      <Sparkles className="w-3.5 h-3.5" />
                    )}
                  </button>
                </div>
              )}
            </div>
          )}
        </div>
      </div>

      <div className="flex items-center gap-2">
        {/* Export Menu */}
        {messageCount > 0 && (
          <div className="relative">
            <button
              onClick={() => setShowMenu(!showMenu)}
              className="p-2 rounded-lg hover:bg-gray-100 text-gray-600 transition-colors"
              title="More options"
            >
              <MoreVertical className="w-4 h-4" />
            </button>

            {showMenu && (
              <>
                <div className="fixed inset-0 z-10" onClick={() => setShowMenu(false)} />
                <div className="absolute right-0 mt-2 w-48 bg-white rounded-lg shadow-lg border border-gray-200 py-1 z-20">
                  <button
                    onClick={() => handleExport('markdown')}
                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                  >
                    <FileText className="w-4 h-4" />
                    <span>Export as Markdown</span>
                  </button>
                  <button
                    onClick={() => handleExport('json')}
                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                  >
                    <FileJson className="w-4 h-4" />
                    <span>Export as JSON</span>
                  </button>
                  <button
                    onClick={() => handleExport('text')}
                    className="w-full flex items-center gap-3 px-4 py-2 text-sm text-gray-700 hover:bg-gray-50"
                  >
                    <File className="w-4 h-4" />
                    <span>Export as Text</span>
                  </button>
                </div>
              </>
            )}
          </div>
        )}

            {!showHistory && (
              <button
                onClick={onNewChat}
                className="flex items-center gap-2 px-3 py-1.5 text-sm bg-joa-primary hover:bg-teal-800 text-white rounded-lg transition-colors"
              >
                <Plus className="w-4 h-4" />
                <span className="hidden sm:inline">New Chat</span>
              </button>
            )}
      </div>
    </div>
  );
}


