import { useState, useCallback } from 'react';
import { API_ENDPOINTS } from '../config/api';

export interface ChatSession {
  id: string;
  shortId: string;
  title: string;
  model: string;
  userId: string;
  autoTitle: boolean;
  createdAt: string;
  updatedAt: string;
  messageCount: number;
}

export interface SessionListResponse {
  sessions: ChatSession[];
  pagination: {
    page: number;
    limit: number;
    total: number;
    pages: number;
  };
}

export function useSessionManagement() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  /**
   * Create a new empty chat session
   */
  const createSession = useCallback(async (title?: string, model?: string): Promise<ChatSession> => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(API_ENDPOINTS.chat.createSession, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title: title || 'New Chat',
          model: model || 'gpt-4-turbo',
        }),
      });

      if (!response.ok) {
        throw new Error(`Failed to create session: ${response.statusText}`);
      }

      const session: ChatSession = await response.json();
      return session;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to create session';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * Load a session by its ID (UUID or shortId)
   */
  const loadSession = useCallback(async (sessionId: string): Promise<ChatSession> => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(API_ENDPOINTS.chat.session(sessionId));

      if (!response.ok) {
        if (response.status === 404) {
          throw new Error('Session not found');
        }
        throw new Error(`Failed to load session: ${response.statusText}`);
      }

      const session: ChatSession = await response.json();
      return session;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to load session';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * List all sessions with optional pagination and search
   */
  const listSessions = useCallback(async (
    page: number = 1,
    limit: number = 20,
    search?: string
  ): Promise<SessionListResponse> => {
    setLoading(true);
    setError(null);
    
    try {
      const params = new URLSearchParams({
        page: page.toString(),
        limit: limit.toString(),
      });

      if (search) {
        params.append('search', search);
      }

      const response = await fetch(`${API_ENDPOINTS.chat.sessions}?${params.toString()}`);

      if (!response.ok) {
        throw new Error(`Failed to fetch sessions: ${response.statusText}`);
      }

      const data: SessionListResponse = await response.json();
      return data;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to fetch sessions';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * Update session title manually
   */
  const updateTitle = useCallback(async (
    sessionId: string,
    title: string,
    autoGenerated: boolean = false
  ): Promise<ChatSession> => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(API_ENDPOINTS.chat.updateTitle(sessionId), {
        method: 'PATCH',
        headers: {
          'Content-Type': 'application/json',
        },
        body: JSON.stringify({
          title,
          autoGenerated,
        }),
      });

      if (!response.ok) {
        throw new Error(`Failed to update title: ${response.statusText}`);
      }

      const session: ChatSession = await response.json();
      return session;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to update title';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * Generate an LLM-powered title for the session
   */
  const generateTitle = useCallback(async (sessionId: string): Promise<ChatSession> => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(API_ENDPOINTS.chat.generateTitle(sessionId), {
        method: 'POST',
      });

      if (!response.ok) {
        if (response.status === 400) {
          throw new Error('Session has no messages yet');
        }
        throw new Error(`Failed to generate title: ${response.statusText}`);
      }

      const session: ChatSession = await response.json();
      return session;
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to generate title';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  /**
   * Delete a session
   */
  const deleteSession = useCallback(async (sessionId: string): Promise<void> => {
    setLoading(true);
    setError(null);
    
    try {
      const response = await fetch(API_ENDPOINTS.chat.deleteSession(sessionId), {
        method: 'DELETE',
      });

      if (!response.ok) {
        throw new Error(`Failed to delete session: ${response.statusText}`);
      }
    } catch (err) {
      const errorMessage = err instanceof Error ? err.message : 'Failed to delete session';
      setError(errorMessage);
      throw new Error(errorMessage);
    } finally {
      setLoading(false);
    }
  }, []);

  return {
    // State
    loading,
    error,
    
    // Methods
    createSession,
    loadSession,
    listSessions,
    updateTitle,
    generateTitle,
    deleteSession,
  };
}


