#!/bin/bash

echo "🔧 Fixing Railway database connections..."

echo "📋 Steps to complete:"
echo ""
echo "1. Go to Railway Dashboard: https://railway.app"
echo "2. Open your project: positive-recreation"
echo "3. Add PostgreSQL database:"
echo "   - Click 'New' → 'Database' → 'PostgreSQL'"
echo "   - Copy the DATABASE_URL from the PostgreSQL service"
echo ""
echo "4. Add Redis database:"
echo "   - Click 'New' → 'Database' → 'Redis'"
echo "   - Copy the REDIS_URL from the Redis service"
echo ""
echo "5. Update backend service with real database URLs:"
echo "   railway variables --set 'DATABASE_URL=<postgres-url>' --service backend"
echo "   railway variables --set 'REDIS_URL=<redis-url>' --service backend"
echo ""
echo "6. Redeploy backend service:"
echo "   cd services/backend && railway up"
echo ""
echo "🔍 Current database URLs (these are wrong - localhost won't work in Railway):"
railway variables --service backend | grep -E "(DATABASE_URL|REDIS_URL)"
echo ""
echo "✅ After adding databases, your backend will be able to connect properly!"
