-- Migration: Add URL tracking fields to chat_sessions table
-- Created: 2025-01-22
-- Purpose: Enable URL-based chat session tracking with short IDs

-- Add new columns to chat_sessions table
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS short_id TEXT;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS slug TEXT;
ALTER TABLE chat_sessions ADD COLUMN IF NOT EXISTS auto_title BOOLEAN DEFAULT FALSE;

-- Create function to generate short IDs for existing sessions
CREATE OR REPLACE FUNCTION generate_short_id() RETURNS TEXT AS $$
DECLARE
    chars TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789';
    result TEXT := '';
    i INTEGER;
BEGIN
    FOR i IN 1..8 LOOP
        result := result || substr(chars, floor(random() * length(chars) + 1)::int, 1);
    END LOOP;
    RETURN result;
END;
$$ LANGUAGE plpgsql;

-- Generate short IDs for existing sessions
-- This ensures backward compatibility with existing data
DO $$
DECLARE
    session_record RECORD;
    new_short_id TEXT;
    max_attempts INTEGER := 10;
    attempt INTEGER;
    id_exists BOOLEAN;
BEGIN
    FOR session_record IN SELECT id FROM chat_sessions WHERE short_id IS NULL LOOP
        attempt := 0;
        LOOP
            new_short_id := generate_short_id();
            
            -- Check if this short_id already exists
            SELECT EXISTS(SELECT 1 FROM chat_sessions WHERE short_id = new_short_id) INTO id_exists;
            
            EXIT WHEN NOT id_exists OR attempt >= max_attempts;
            
            attempt := attempt + 1;
        END LOOP;
        
        IF attempt >= max_attempts THEN
            RAISE EXCEPTION 'Could not generate unique short_id for session %', session_record.id;
        END IF;
        
        UPDATE chat_sessions SET short_id = new_short_id WHERE id = session_record.id;
    END LOOP;
END $$;

-- Make short_id NOT NULL after populating existing records
ALTER TABLE chat_sessions ALTER COLUMN short_id SET NOT NULL;

-- Make auto_title NOT NULL with default
ALTER TABLE chat_sessions ALTER COLUMN auto_title SET NOT NULL;
ALTER TABLE chat_sessions ALTER COLUMN auto_title SET DEFAULT FALSE;

-- Add unique constraint on short_id
ALTER TABLE chat_sessions ADD CONSTRAINT chat_sessions_short_id_unique UNIQUE (short_id);

-- Add index for fast lookups by short_id
CREATE INDEX IF NOT EXISTS chat_sessions_short_id_idx ON chat_sessions(short_id);

-- Add index for slug (if used for readable URLs)
CREATE INDEX IF NOT EXISTS chat_sessions_slug_idx ON chat_sessions(slug) WHERE slug IS NOT NULL;

-- Add comment for documentation
COMMENT ON COLUMN chat_sessions.short_id IS 'Unique 8-character alphanumeric identifier for URL routing (e.g., aB3dE7fG)';
COMMENT ON COLUMN chat_sessions.slug IS 'Optional URL-friendly slug derived from title';
COMMENT ON COLUMN chat_sessions.auto_title IS 'Indicates if title was auto-generated by LLM (true) or manually set (false)';

-- Drop the temporary function
DROP FUNCTION IF EXISTS generate_short_id();


